### PR TITLE
[view] Blade Components

### LINKED ISSUE #174: Anonymous Balde X components not working
Hello.
I am running `components/view` as it is mentioned here https://github.com/mattstauffer/Torch/tree/master/components/view#usage, but when I try adding anonymous component, I get an error.

Updated `templates/page.blade.php`:

    @extends('layout')

    @section('content')

        <h1>{{ $title }}</h1>
        <p>{{ $text }}</p>

        <x-alert type="success" message="Good luck!" />

    @endsection

The `templates/components/alert.blade.php`:

    @props([
        'type' => 'info',
        'message'
    ])
    
    <div {{ $attributes->merge(['class' => 'alert alert-' . $type]) }}>
        {{ $message }}
    </div>

The error:

    Illuminate\Contracts\Container\BindingResolutionException thrown with message 
    "Target [Illuminate\Contracts\View\Factory] is not instantiable."

    Stacktrace:
    #33 Illuminate\Contracts\Container\BindingResolutionException in 
    C:\OpenServer\domains\view\vendor\illuminate\container\Container.php:1017
    #32 Illuminate\Container\Container:notInstantiable in 
    C:\OpenServer\domains\view\vendor\illuminate\container\Container.php:818
    #31 Illuminate\Container\Container:build in C:\OpenServer\domains\view\vendor\illuminate\container\Container.php:691
    #30 Illuminate\Container\Container:resolve in C:\OpenServer\domains\view\vendor\illuminate\container\Container.php:637
    #29 Illuminate\Container\Container:make in 
    C:\OpenServer\domains\view\vendor\illuminate\view\Compilers\ComponentTagCompiler.php:221
    #28 Illuminate\View\Compilers\ComponentTagCompiler:componentClass in 
    C:\OpenServer\domains\view\vendor\illuminate\view\Compilers\ComponentTagCompiler.php:185
    #27 Illuminate\View\Compilers\ComponentTagCompiler:componentString in 
    C:\OpenServer\domains\view\vendor\illuminate\view\Compilers\ComponentTagCompiler.php:170
    #26 Illuminate\View\Compilers\ComponentTagCompiler:Illuminate\View\Compilers\{closure} in [internal]:0
    #25 preg_replace_callback in 
    C:\OpenServer\domains\view\vendor\illuminate\view\Compilers\ComponentTagCompiler.php:165
    #24 Illuminate\View\Compilers\ComponentTagCompiler:compileSelfClosingTags in             
    C:\OpenServer\domains\view\vendor\illuminate\view\Compilers\ComponentTagCompiler.php:79
    #23 Illuminate\View\Compilers\ComponentTagCompiler:compileTags in 
    C:\OpenServer\domains\view\vendor\illuminate\view\Compilers\ComponentTagCompiler.php:66
    #22 Illuminate\View\Compilers\ComponentTagCompiler:compile in 
    C:\OpenServer\domains\view\vendor\illuminate\view\Compilers\BladeCompiler.php:322
    #21 Illuminate\View\Compilers\BladeCompiler:compileComponentTags in 
    C:\OpenServer\domains\view\vendor\illuminate\view\Compilers\BladeCompiler.php:222
    #20 Illuminate\View\Compilers\BladeCompiler:compileString in 
    C:\OpenServer\domains\view\vendor\illuminate\view\Compilers\BladeCompiler.php:143
    #19 Illuminate\View\Compilers\BladeCompiler:compile in 
    C:\OpenServer\domains\view\vendor\illuminate\view\Engines\CompilerEngine.php:51
    #18 Illuminate\View\Engines\CompilerEngine:get in C:\OpenServer\domains\view\vendor\illuminate\view\View.php:139
    #17 Illuminate\View\View:getContents in C:\OpenServer\domains\view\vendor\illuminate\view\View.php:122
    #16 Illuminate\View\View:renderContents in C:\OpenServer\domains\view\vendor\illuminate\view\View.php:91
    #15 Illuminate\View\View:render in C:\OpenServer\domains\view\index.php:57
    #14 Closure:{closure} in C:\OpenServer\domains\view\vendor\slim\slim\Slim\Handlers\Strategies\RequestResponse.php:40
    #13 call_user_func in C:\OpenServer\domains\view\vendor\slim\slim\Slim\Handlers\Strategies\RequestResponse.php:40
    #12 Slim\Handlers\Strategies\RequestResponse:__invoke in 
    C:\OpenServer\domains\view\vendor\slim\slim\Slim\Route.php:281
    #11 Slim\Route:__invoke in C:\OpenServer\domains\view\vendor\slim\slim\Slim\MiddlewareAwareTrait.php:117
    #10 Slim\Route:callMiddlewareStack in C:\OpenServer\domains\view\vendor\slim\slim\Slim\Route.php:268
    #9 Slim\Route:run in C:\OpenServer\domains\view\vendor\slim\slim\Slim\App.php:503
    #8 Slim\App:__invoke in C:\OpenServer\domains\view\vendor\zeuxisoo\slim- 
    whoops\src\Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware.php:31
    #7 Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware:__invoke in 
    C:\OpenServer\domains\view\vendor\slim\slim\Slim\DeferredCallable.php:57
    #6 call_user_func_array in C:\OpenServer\domains\view\vendor\slim\slim\Slim\DeferredCallable.php:57
    #5 Slim\DeferredCallable:__invoke in C:\OpenServer\domains\view\vendor\slim\slim\Slim\MiddlewareAwareTrait.php:70
    #4 call_user_func in C:\OpenServer\domains\view\vendor\slim\slim\Slim\MiddlewareAwareTrait.php:70
    #3 Slim\App:Slim\{closure} in C:\OpenServer\domains\view\vendor\slim\slim\Slim\MiddlewareAwareTrait.php:117
    #2 Slim\App:callMiddlewareStack in C:\OpenServer\domains\view\vendor\slim\slim\Slim\App.php:392
    #1 Slim\App:process in C:\OpenServer\domains\view\vendor\slim\slim\Slim\App.php:297
    #0 Slim\App:run in C:\OpenServer\domains\view\index.php:60

Please help.

### PR DESCRIPTION
**Pull request by Gummibeer**
fixes #174 
blocked by #180

### CODE REVIEW

File: components/view/index.php [hunk 1]
```diff
@@ -49,11 +59,15 @@
     });
 
     $viewResolver->register('php', function () {
-        return new PhpEngine;
+        return new PhpEngine(new Filesystem());
     });
```
Comment (Juhlinus) [inline components/view/index.php:63]: Can do this instead
```
$viewResolver->register('php', function () use ($filesystem) {
    return new PhpEngine($filesystem);
});
```

Comment (Gummibeer) [reply components/view/index.php:63]: I will bind it to the container properly as it's done in a real Laravel app.
But yes, good catch - thanks! 😊

File: components/view/index.php [hunk 2]
```diff
@@ -49,11 +53,15 @@
...
 
     $viewResolver->register('php', function () {
-        return new PhpEngine;
+        return App::getInstance()->make(PhpEngine::class);
```
Comment (Juhlinus) [inline components/view/index.php:56]: Does this work? The PhpEngine class has not been bound anywhere, so it shouldn't right?

Comment (Gummibeer) [reply components/view/index.php:56]: It does as the container will call `new` with dependency injection for unbound classes.
A reason why you should avoid `new` calls in general in packages but also in your own code to make it easier to override a class or always call a method on/after initialization.
It will also try to get all dependencies from container or initialize them the same way as the requested class.

Comment (Juhlinus) [reply components/view/index.php:56]: Oh, cool I did not know that.

Comment (Juhlinus) [reply components/view/index.php:56]: Shouldn't this be done with `return new CompilerEngine($bladeCompiler);` then as well?

Comment (mattstauffer) [reply components/view/index.php:56]: I've mainly tried to avoid using any features of Slim other than routing.

And I've tried to keep the build steps *super* clear so that folks who don't *absolutely* have to use the Illuminate container don't have to.

Without having read the code, I would prefer we avoid pulling anything out of the container unless absolutely necessary.

Comment (mattstauffer) [reply components/view/index.php:56]: OK, reading the code, I'd prefer we keep it as `new ` if possible.

> For the blade engine this would lead to a lot more changes as all the dependencies would have to be added to the container.

Does that mean the old PHPEngine didn't have all these dependencies but the new one does?

Thanks!

File: src/App.php [hunk 3]
```diff
@@ -15,17 +15,30 @@ public function isDownForMaintenance(): bool
...
-        if(!empty($environments)) {
-            return in_array('torch', $environments);
+        if(empty($environments)) {
+            return 'torch';
         }
 
-        return 'torch';
+        return in_array(
+            'torch',
+            is_array($environments[0]) ? $environments[0] : $environments
```
Comment (mattstauffer) [inline src/App.php:31]: Just for my curiosity, in what case would we be passing an array whose first index would be an array of environments? Thanks!

**Review by mattstauffer — CHANGES_REQUESTED** [review]

File: components/view/index.php (hunk 2 above)
Comment (Gummibeer) [reply components/view/index.php:56]: The PhpEngine change was only as PhpStorm complained about missing construct call. Haven't checked if that changed somewhen or it never worked but hasn't been a problem as we use the blade engine only in the example.

For this component slim is "useless" as it's a single route - so a plain index.php would be the same as the current construct.
So if you want to keep it simple I would say that we. can remove slim here.

Regarding the container: even if it's already required? So this component doesn't work without container as the internals use the container.
So I agree that we shouldn't use it just for comfort - but if it's already required we could use its full potential!?

File: components/view/index.php [hunk 4]
```diff
@@ -24,6 +25,8 @@
  * @source https://github.com/illuminate/view
  */
 
+App::getInstance()->instance(\Illuminate\Contracts\Foundation\Application::class, App::getInstance());
```
[the remark this answers is not in the document]
Comment (Gummibeer) [reply components/view/index.php:28]: Okay, the reason is that the internals use this binding - will add a comment.

File: src/App.php (hunk 3 above)
Comment (Gummibeer) [reply src/App.php:31]: It's because of the `...` opperator.
```php
environment('a', 'b') => ['a', 'b']
environment(['a', 'b']) => [['a', 'b']]
```
This part is copied from the illuminate core - I think if we have this example class it should be fully compatible with the interface - even if we don't implement it as we don't need all methods.

Comment (mattstauffer) [reply src/App.php:31]: 👍  Sounds good, thanks!

File: components/view/index.php (hunk 4 above)
[the remark this answers is not in the document]
Comment (mattstauffer) [reply components/view/index.php:28]: Right, I just mean--will we add this binding in *every* sample that uses this included App? if so, could we just move it there?

File: components/view/index.php (hunk 2 above)
Comment (mattstauffer) [reply components/view/index.php:56]: I'd still like to avoid using its full potential, because I know folks may choose to use other forms of IOC/dependency injection, so I'd like what we're doing to be laid out in its full, ugly glory :)

File: components/view/index.php (hunk 4 above)
[the remark this answers is not in the document]
Comment (Gummibeer) [reply components/view/index.php:28]: No, it's special to this one as all the others don't need this binding.
As it's special I would keep it special!?

[the remark this answers is not in the document]
Comment (Gummibeer) [reply components/view/index.php]: https://github.com/mattstauffer/Torch/pull/181/commits/8b9475369d42fce12891fa2418a96bfb08b40e78

File: components/view/index.php (hunk 2 above)
Comment (Gummibeer) [reply components/view/index.php]: Long discussion - short solution: the PhpEngine is now fully removed 😂
It's not needed for blade and those who want to use PHP templates should use `include` 😉

File: components/view/index.php (hunk 4 above)
[the remark this answers is not in the document]
Comment (mattstauffer) [reply components/view/index.php]: Got it, yep!

**Comment by mattstauffer** [comment]
Freaking love it. Thank you!
